PygmentsCodeFences = true
PygmentsStyle = "monokai"
archetypeDir = "archetypes"
baseURL = "https://mattdav.is"
buildDrafts = false
buildExpired = false
buildFuture = false
canonifyURLs = false
contentDir = "content"
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
dataDir = "data"
disable404 = false
disableHugoGeneratorInject = false
disableRSS = false
disableSitemap = false
enableEmoji = true
enableGitInfo = false
enableMissingTranslationPlaceholders = false
enableRobotsTXT = true
languageCode = "en-us"
layoutDir = "layouts"
paginate = 10
publishDir = "public"
rssLimit = 10
theme = "terminal-blog"
title = "/mattdav.is"
[author]
name = "Matt Davis"
[blackfriday]
hrefTargetBlank = true
[languages.en]
copyright = "<a href=\"https://creativecommons.org/licenses/by-nc/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY-NC 4.0</a>"
subtitle = "live from atx"
weight = 1
[[menu.main]]
identifier = "photos"
name = "/photos"
url = "photos/"
weight = 3
[[menu.main]]
identifier = "tools"
name = "/tools"
url = "/tools"
weight = 5
[[menu.main]]
identifier = "projects"
name = "/portfolio"
url = "portfolio/"
weight = 4
[[menu.main]]
identifier = "posts"
name = "/blog"
url = "posts/"
weight = 2
[[menu.main]]
identifier = "about"
name = "/about"
url = "about/"
weight = 1
[params]
customCSS = []
customJS = []
dateform = "Jan 2, 2006"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04"
dateformShort = "Jan 2"
description = "Personal blog of Matt Davis - Austin, TX"
disableReadOtherPosts = false
enableGlobalLanguageMenu = false
enableSharingButtons = true
enableThemeToggle = true
homeSubtitle = "my little slice of the internet"
images = [""]
justifyContent = false
keywords = "austin, web developer, screen geeks, enterprise architect, sales engineer"
[params.favicon.color]
mask = "#1b1c1d"
msapplication = "#1b1c1d"
theme = "#1b1c1d"
[params.footer]
author = true
copyright = false
rss = false
topText = []
trademark = false
[params.logo]
logoHomeLink = "/"
logoMark = ">"
logoText = "$ cd /home/mattd"
[params.portrait]
alt = "Portrait"
maxWidth = "200px"
path = "/img/profile.jpg"
[[params.social]]
name = "twitter"
url = "https://twitter.com/codewithMatt"
[[params.social]]
name = "email"
url = "mailto:me@mattdav.is"
[[params.social]]
name = "github"
url = "https://github.com/dattmavis"
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/matt-davis-665265213/"
[permalinks]
posts = "/posts/:year/:month/:title/"
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
